### ISSUE TITLE
cant update, manifest unkown

### ISSUE THREAD

**Issue by Jackahack** [cavaliere78/calibre_web_plus#1]
i get the following error when i try to update to 0.952: 
`Can't install cavaliere78/armv7-addon-calibre:0.952: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.952&fromImage=cavaliere78%2Farmv7-addon-calibre&platform=linux%2Farm64: Not Found ("manifest for cavaliere78/armv7-addon-calibre:0.952 not found: manifest unknown: manifest unknown")` 

is this something local or not?

**Comment by cavaliere78** [comment]
I know I'm try to solve.

**Comment by cavaliere78** [comment]
Issue solved plaese install the latest version
